development:
  patients:
    count: 2
    traits:
      - overdue
      - hypertensive
    medical_histories: 1
    prescription_drugs: 1
    blood_pressures: 3
    appointments: 2

test:
  patients:
    count: 3
    traits:
      - overdue
      - hypertensive
    medical_histories: 3
    prescription_drugs: 3
    blood_pressures: 3
    appointments: 3

sandbox:
  patients:
    count: 3
    traits:
      - overdue
      - hypertensive
    medical_histories: 3
    prescription_drugs: 3
    blood_pressures: 3
    appointments: 3