name: Linux Container Node Workflow

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Step 1: Log in to Azure Container Registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: simpleserverregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    # Step 2: Build and Push Docker image with Docker Compose
    - run: |
        docker-compose -f .docker/docker-compose.yml build  # Adjust path to docker-compose if necessary
        docker-compose -f .docker/docker-compose.yml push   # Push to ACR

    # Step 3: Deploy Docker image to Azure Web App
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'simple-server'  # Your Azure Web App's name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # The publish profile
        images: 'simpleserverregistry.azurecr.io/simple-server:${{ github.sha }}'  # The image from ACR
