name: Linux Container Node Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: simpleserverregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t simpleserverregistry.azurecr.io/simple-server:${{ github.sha }}
        docker push simpleserverregistry.azurecr.io/simple-server:${{ github.sha }}


    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'simple-server'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'simpleserverregistry.azurecr.io/simple-server:${{ github.sha }}'
